version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: payouts_postgres
    restart: always
    environment:
      POSTGRES_DB: payouts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payouts_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payouts_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payouts_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres_secure_pass@db:5432/payouts_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=9a6e3d23ab5f5a8946777a829f0aee0f0190bd0234a98a002bc
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - SYSTEM_CURRENCY=INR
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payouts_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
